name: Deploy to GAS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Create clasprc.json
        run: |
          cat <<EOF > ~/.clasprc.json
          ${{ secrets.CLASPRC_JSON }}
          EOF

      - name: Create clasp project binding
        run: echo '{"scriptId":"1NiJ94p1UVFGxd3DrNXz0x3MFC1haPopa11LQy593-3ft4exsoJM4huwZ","rootDir":"."}' > .clasp.json

      - name: Push to GAS
        run: clasp push -f

      - name: Create library version
        run: clasp version "BMSG Universe shared writer $GITHUB_SHA"
